--------------------------------------------------------
--  파일이 생성됨 - 금요일-6월-07-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TEST1
--------------------------------------------------------

  CREATE TABLE "C##TESTDB"."TEST1" 
   (	"ID" VARCHAR2(30 BYTE), 
	"PASS" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##TESTDB.TEST1
SET DEFINE OFF;
Insert into C##TESTDB.TEST1 (ID,PASS) values ('asd','asd');
Insert into C##TESTDB.TEST1 (ID,PASS) values ('qwe','123');
Insert into C##TESTDB.TEST1 (ID,PASS) values ('zxc','213');
Insert into C##TESTDB.TEST1 (ID,PASS) values ('as','as');
Insert into C##TESTDB.TEST1 (ID,PASS) values ('qwe21','213');
--------------------------------------------------------
--  DDL for Index SYS_C008328
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##TESTDB"."SYS_C008328" ON "C##TESTDB"."TEST1" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table TEST1
--------------------------------------------------------

  ALTER TABLE "C##TESTDB"."TEST1" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##TESTDB"."TEST1" MODIFY ("PASS" NOT NULL ENABLE);
  ALTER TABLE "C##TESTDB"."TEST1" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
