--------------------------------------------------------
--  파일이 생성됨 - 금요일-6월-07-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TEST1
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."TEST1" 
   (	"ID" VARCHAR2(20 BYTE), 
	"PASS" VARCHAR2(30 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.TEST1
SET DEFINE OFF;
Insert into SYSTEM.TEST1 (ID,PASS) values ('zxc','123');
Insert into SYSTEM.TEST1 (ID,PASS) values ('asd','123');
Insert into SYSTEM.TEST1 (ID,PASS) values ('qwe','123');
--------------------------------------------------------
--  DDL for Index SYS_C008331
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008331" ON "SYSTEM"."TEST1" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table TEST1
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TEST1" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TEST1" MODIFY ("PASS" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TEST1" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
